services:

  database:
    container_name: database
    build: 
      context: ./database
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: cases123
      MYSQL_HOST: database
  
  webapp:
    container_name: webapp
    build:
      context: ./webapp
      dockerfile: ./Dockerfile

    ports:
      - 80:80
    depends_on:
      - database